version: '2'
services:
  backend:
    build: ./mynewproject
    command: python ./manage.py runserver 0.0.0.0:8000
    ports:
    - 8000:8000
    volumes:
    - ./mynewproject:/data
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
  db:
    image: postgres:9.4
  redis:
    image: redis:5
  frontend:
    build: ./frontend
    command: npm start
    ports:
    - 3000:3000
    volumes:
    - ./frontend:/frontend